replicaCount: 1

image:
  repository: registry.minter.network/minter-org
  pullPolicy: Always

imagePullSecrets:
  - name: registry.minter.network

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true

podSecurityContext: {}

securityContext: {}

service:
  port: 80

ingress:
  domain: minter.org
  tlsname: minter.org

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
